### PR TITLE
Ranged creeps, part 1 - Spawn function

### PR DESCRIPTION
**Pull request by Clauvin**
A small PR that starts work on the spawning creeps.

I'm going to do small PRs instead of a big one with all the creeps' features at once. if there isn't any objection to that.

Features:

* It adds a creep to the center of the map; (it's using the zombie 3D model as trying to use the Yeti mentioned at Discord ended up not working as intended - namely, its idle animation did not trigger, without a clear error message of the why)

Questions:

* Do we have the permission to use the zombie model and animations currently at the assets folder? They were there at the main branch, so I assumed that we had, but better to ask than to assume.

Steps of the next PR:

* Pathfinding on three different routes towards red_dot and blue_dot;
* Regular spawn of ranged creeps, that move towards their opposite team's dots using the pathfinding.

### CODE REVIEW

**Comment by chaosprint** [comment]
Yes, the resources in the assets folders are all fair to use.

**Comment by chaosprint** [comment]
One thing that needs to be fixed is the collider of the Zombie. It seems that the collider is not there as the hero can just walk through the zombie, but the collider should be quite easy to add as I had it on my previous demo video in Discord. You can use the return of `physics::move_character` which is a collision info in 3 dimensions to determine whether the hero should stop.

**Comment by chaosprint** [comment]
There is some Zombie logic I have already written in our FPS template.

You can refer to that one as well https://github.com/AmbientRun/afps

Our goal is to make it sharable between these two templates as the zombie should attack any hero that approaches it.

**Comment by Clauvin** [comment]
> One thing that needs to be fixed is the collider of the Zombie. It seems that the collider is not there as the hero can just walk through the zombie, but the collider should be quite easy to add as I had it on my previous demo video in Discord. You can use the return of `physics::move_character` which is a collision info in 3 dimensions to determine whether the hero should stop.

Right, will work on that now.

**Comment by Clauvin** [comment]
> There is some Zombie logic I have already written in our FPS template.
> 
> You can refer to that one as well https://github.com/AmbientRun/afps
> 
> Our goal is to make it sharable between these two templates as the zombie should attack any hero that approaches it.

Thanks, I figured out what was wrong with the collision thanks to your code!

-----

Ok, collision between player character and creep is working properly now 👍

**Comment by chaosprint** [comment]
> 

Nice, can you create an issue and briefly summarise what you plan to add? 
I can merge this as "part 1" but what is the plan for the rest?
We can discuss in the issue about the overall plan inside the issue. One thing to note is that the modding system is likely to have changes soon so we should consider that as well.

**Comment by Clauvin** [comment]
> Nice, can you create an issue and briefly summarise what you plan to add? 

Sure, can do that.

**Comment by Clauvin** [comment]
Issue made: https://github.com/AmbientRun/amoba/issues/2 .

Also:

* should I keep pinging you on Discord when I do a PR or PR update, or just doing those is enough?
* hang on, which changes will happen to the current mod system?

**Comment by chaosprint** [comment]
> Issue made: #2 .
> 
> Also:
> 
> * should I keep pinging you on Discord when I do a PR or PR update, or just doing those is enough?
> * hang on, which changes will happen to the current mod system?

For minor details, we can chat on Discord rather than make posts here. Issues are good for summarising and documenting all the ideas and changes, linking to PRs. As for the modding system, @philpax is working on some new features here https://github.com/AmbientRun/Ambient/tree/enum-support

But I have the same question on how that would influence the current code structure. @philpax

**Comment by philpax** [comment]
Hey! Each separate WASM binary will belong to their own ember, so that they can define their own components etc, without being fused together. Embers can depend on each other. It'll be like defining separate packages for each of your modules, instead of having them all under one package.

The details are still being worked on, but you can get an idea of what it might look like by looking around here https://github.com/AmbientRun/Ambient/tree/enum-support/guest/rust/examples/basics/dependencies

**Comment by Clauvin** [comment]
Ok, got it!

@chaosprint given that this PR is the first of more PRs that will add more functionality to creeps until the ranged creeps are working properly, should it be merged into AmbientRun:main, or to a different branch for #2 until #2 is finished and then the whole branch is merged with AmbientRun:main?

**Comment by chaosprint** [comment]
> Ok, got it!
> 
> @chaosprint given that this PR is the first of more PRs that will add more functionality to creeps until the ranged creeps are working properly, should it be merged into AmbientRun:main, or to a different branch for #2 until #2 is finished and then the whole branch is merged with AmbientRun:main?

IMHO, to have something more complete would be better. So I would suggest the latter.

**Comment by Clauvin** [comment]
> > Ok, got it!
> > @chaosprint given that this PR is the first of more PRs that will add more functionality to creeps until the ranged creeps are working properly, should it be merged into AmbientRun:main, or to a different branch for #2 until #2 is finished and then the whole branch is merged with AmbientRun:main?
> 
> IMHO, to have something more complete would be better. So I would suggest the latter.

Agreed - closing the PR, will see if I can make another one with the same content, but for a different branch.

**Comment by Clauvin** [comment]
Ok, can't create a new branch on AmbientRun/amoba, will make a PR once the code is good enough or a branch for piece-by-piece PRs is made.

**Pull request closed without merging**
